language: node_js

node_js:
  - 12

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn add codecov.io coveralls

cache:
  yarn: true
  directories:
    - '~/.npm'
    - '~/.cache'
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn run travis
  - yarn run build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
